language: go
go:
  - 1.9

install: true

before_script:
  # 环境错误
  - rm -rf spider.go

script:
   - go run cmd/question_utils.go -s="issue"

after_script:
  - git add *.data
  - git commit -m "auto update data"
  - git push -f --quiet

branches:
  only:
    - master
env:
  global:
    - GH_REF: github.com/sundy-li/wechat_brain.git